/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '../../..';
import * as PrivategptApi from '../../../../api';
import * as core from '../../../../core';

export const EmbeddingsBodyInput: core.serialization.Schema<
  serializers.EmbeddingsBodyInput.Raw,
  PrivategptApi.EmbeddingsBodyInput
> = core.serialization.undiscriminatedUnion([
  core.serialization.string(),
  core.serialization.list(core.serialization.string()),
]);

export declare namespace EmbeddingsBodyInput {
  type Raw = string | string[];
}
