/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const ContextFilter: core.serialization.ObjectSchema<
  serializers.ContextFilter.Raw,
  PrivategptApi.ContextFilter
> = core.serialization.object({
  docsIds: core.serialization.property(
    'docs_ids',
    core.serialization.list(core.serialization.string()).optional(),
  ),
});

export declare namespace ContextFilter {
  interface Raw {
    docs_ids?: string[] | null;
  }
}
