/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const Embedding: core.serialization.ObjectSchema<
  serializers.Embedding.Raw,
  PrivategptApi.Embedding
> = core.serialization.object({
  index: core.serialization.number(),
  object: core.serialization.unknown(),
  embedding: core.serialization.list(core.serialization.number()),
});

export declare namespace Embedding {
  interface Raw {
    index: number;
    object?: unknown;
    embedding: number[];
  }
}
