/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const OpenAiMessageRole: core.serialization.Schema<
  serializers.OpenAiMessageRole.Raw,
  PrivategptApi.OpenAiMessageRole
> = core.serialization.enum_(['assistant', 'system', 'user']);

export declare namespace OpenAiMessageRole {
  type Raw = 'assistant' | 'system' | 'user';
}
