/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '../../../..';
import * as PrivategptApi from '../../../../../api';
import * as core from '../../../../../core';

export const EmbeddingsBody: core.serialization.Schema<
  serializers.EmbeddingsBody.Raw,
  PrivategptApi.EmbeddingsBody
> = core.serialization.object({
  input: core.serialization.lazy(
    async () => (await import('../../../..')).EmbeddingsBodyInput,
  ),
});

export declare namespace EmbeddingsBody {
  interface Raw {
    input: serializers.EmbeddingsBodyInput.Raw;
  }
}
