/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PrivategptApi from '../../../..';

/**
 * @example
 *     {}
 */
export interface EmbeddingsBody {
  input: PrivategptApi.EmbeddingsBodyInput;
}
