/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PrivategptApi from '../../../..';

/**
 * @example
 *     {
 *         text: "string",
 *         contextFilter: {}
 *     }
 */
export interface ChunksBody {
  text: string;
  contextFilter?: PrivategptApi.ContextFilter;
  limit?: number;
  prevNextChunks?: number;
}
