/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OpenAiCompletionObject = 'completion' | 'completion.chunk';

export const OpenAiCompletionObject = {
  Completion: 'completion',
  CompletionChunk: 'completion.chunk',
} as const;
