/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PrivategptApi from '..';

/**
 * Clone of OpenAI Completion model.
 *
 * For more information see: https://platform.openai.com/docs/api-reference/chat/object
 */
export interface OpenAiCompletion {
  id: string;
  object?: PrivategptApi.OpenAiCompletionObject;
  created: number;
  model?: unknown;
  choices: PrivategptApi.OpenAiChoice[];
}
