/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PrivategptApi from '..';

export interface ValidationError {
  loc: PrivategptApi.ValidationErrorLocItem[];
  msg: string;
  type: string;
}
