/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fileName: "string",
 *         text: "string"
 *     }
 */
export interface IngestTextBody {
  fileName: string;
  text: string;
}
