/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PrivategptApi from '..';

/**
 * Response from AI.
 *
 * Either the delta or the message will be present, but never both.
 * Sources used will be returned in case context retrieval was enabled.
 */
export interface OpenAiChoice {
  finishReason?: string;
  delta?: PrivategptApi.OpenAiDelta;
  message?: PrivategptApi.OpenAiMessage;
  sources?: PrivategptApi.Chunk[];
  index?: number;
}
