/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A piece of completion that needs to be concatenated to get the full message.
 */
export interface OpenAiDelta {
  content?: string;
}
