/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from '../../errors';
import * as PrivategptApi from '..';

export class UnprocessableEntityError extends errors.PrivategptApiError {
  constructor(body: PrivategptApi.HttpValidationError) {
    super({
      message: 'UnprocessableEntityError',
      statusCode: 422,
      body: body,
    });
    Object.setPrototypeOf(this, UnprocessableEntityError.prototype);
  }
}
