/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const EmbeddingsResponse: core.serialization.ObjectSchema<
  serializers.EmbeddingsResponse.Raw,
  PrivategptApi.EmbeddingsResponse
> = core.serialization.object({
  object: core.serialization.unknown(),
  model: core.serialization.unknown(),
  data: core.serialization.list(
    core.serialization.lazyObject(async () => (await import('..')).Embedding),
  ),
});

export declare namespace EmbeddingsResponse {
  interface Raw {
    object?: unknown;
    model?: unknown;
    data: serializers.Embedding.Raw[];
  }
}
