/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const HealthResponse: core.serialization.ObjectSchema<
  serializers.HealthResponse.Raw,
  PrivategptApi.HealthResponse
> = core.serialization.object({
  status: core.serialization.unknown().optional(),
});

export declare namespace HealthResponse {
  interface Raw {
    status?: unknown | null;
  }
}
