/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const OpenAiDelta: core.serialization.ObjectSchema<
  serializers.OpenAiDelta.Raw,
  PrivategptApi.OpenAiDelta
> = core.serialization.object({
  content: core.serialization.string().optional(),
});

export declare namespace OpenAiDelta {
  interface Raw {
    content?: string | null;
  }
}
