/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '../../../..';
import * as PrivategptApi from '../../../../../api';
import * as core from '../../../../../core';

export const IngestTextBody: core.serialization.Schema<
  serializers.IngestTextBody.Raw,
  PrivategptApi.IngestTextBody
> = core.serialization.object({
  fileName: core.serialization.property(
    'file_name',
    core.serialization.string(),
  ),
  text: core.serialization.string(),
});

export declare namespace IngestTextBody {
  interface Raw {
    file_name: string;
    text: string;
  }
}
