/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const ChunksResponse: core.serialization.ObjectSchema<
  serializers.ChunksResponse.Raw,
  PrivategptApi.ChunksResponse
> = core.serialization.object({
  object: core.serialization.unknown(),
  model: core.serialization.unknown(),
  data: core.serialization.list(
    core.serialization.lazyObject(async () => (await import('..')).Chunk),
  ),
});

export declare namespace ChunksResponse {
  interface Raw {
    object?: unknown;
    model?: unknown;
    data: serializers.Chunk.Raw[];
  }
}
