/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const IngestedDoc: core.serialization.ObjectSchema<
  serializers.IngestedDoc.Raw,
  PrivategptApi.IngestedDoc
> = core.serialization.object({
  object: core.serialization.unknown(),
  docId: core.serialization.property('doc_id', core.serialization.string()),
  docMetadata: core.serialization.property(
    'doc_metadata',
    core.serialization
      .record(core.serialization.string(), core.serialization.unknown())
      .optional(),
  ),
});

export declare namespace IngestedDoc {
  interface Raw {
    object?: unknown;
    doc_id: string;
    doc_metadata?: Record<string, unknown> | null;
  }
}
