/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const IngestResponse: core.serialization.ObjectSchema<
  serializers.IngestResponse.Raw,
  PrivategptApi.IngestResponse
> = core.serialization.object({
  object: core.serialization.unknown(),
  model: core.serialization.unknown(),
  data: core.serialization.list(
    core.serialization.lazyObject(async () => (await import('..')).IngestedDoc),
  ),
});

export declare namespace IngestResponse {
  interface Raw {
    object?: unknown;
    model?: unknown;
    data: serializers.IngestedDoc.Raw[];
  }
}
