/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const OpenAiCompletionObject: core.serialization.Schema<
  serializers.OpenAiCompletionObject.Raw,
  PrivategptApi.OpenAiCompletionObject
> = core.serialization.enum_(['completion', 'completion.chunk']);

export declare namespace OpenAiCompletionObject {
  type Raw = 'completion' | 'completion.chunk';
}
