/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from '..';
import * as PrivategptApi from '../../api';
import * as core from '../../core';

export const OpenAiMessage: core.serialization.ObjectSchema<
  serializers.OpenAiMessage.Raw,
  PrivategptApi.OpenAiMessage
> = core.serialization.object({
  role: core.serialization
    .lazy(async () => (await import('..')).OpenAiMessageRole)
    .optional(),
  content: core.serialization.string().optional(),
});

export declare namespace OpenAiMessage {
  interface Raw {
    role?: serializers.OpenAiMessageRole.Raw | null;
    content?: string | null;
  }
}
