/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PrivategptApi from '..';

export interface EmbeddingsResponse {
  object?: unknown;
  model?: unknown;
  data: PrivategptApi.Embedding[];
}
