/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OpenAiMessageRole = 'assistant' | 'system' | 'user';

export const OpenAiMessageRole = {
  Assistant: 'assistant',
  System: 'system',
  User: 'user',
} as const;
