name: Node.js Package

on:
  release:
    types: [created]

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.7.1
      - uses: actions/setup-node@v4
      
        with:
          node-version: '20.x'
      - run: pnpm install
      - run: pnpm build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.7.1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist 
          path: ./dist
      - run: cp package.json ./dist
      - run: pnpm publish dist --access public --no-git-checks

